### ISSUE TITLE
Letter spacing and my playlists missing

### ISSUE THREAD

**Issue by janabouc** [sethgecko13/MeeZeeFit#13]
I left a review❤️.![Uploading 269664603...]

Opening the latest TestFlight version my playlists have disappeared again. Also the +playlist label is broken into 2 lines with the final "t" on the line below "+Playlis". Same with "YouTub" with "e" on next line. Comments also "comm" and "ents" underneath (should be "com-" "ments" if intentionally splitting. 

My ios settings for Display = Default. Under accessibility I have "Larger text" on 
"For apps that support Dynamic Type" 
But its set only 1 notch above normal. 

This is on iPhone 14 Pro Max ios 16.6.1.

**Comment by janabouc** [comment]
![image](https://github.com/sethgecko13/MeeZeeFit/assets/60453297/7a3c1444-0d13-404f-817a-19ee889da764)

**Comment by janabouc** [comment]
So i added one video which showed on the previously empty playlist tab page. Then i clicked the clear button and a list of previously created playlists appeared with my actual playlists intact but they don't otherwise appear on playlist page.![image](https://github.com/sethgecko13/MeeZeeFit/assets/60453297/843443d1-e806-4e77-a336-d3370b47f26e) ![image](https://github.com/sethgecko13/MeeZeeFit/assets/60453297/921506c1-43bb-4dcd-a55b-2aea519e113e)

**Comment by janabouc** [comment]
"Shuffle" also split into 2 lines![image](https://github.com/sethgecko13/MeeZeeFit/assets/60453297/3c8d663a-fc4e-4f19-95e1-5f959b0202f2)

**Comment by sethgecko13** [comment]
Review: thanks!

spacing: thanks!  Will fix.

playlists disappearing:  I know what’s happening.  I could explain it, but it’s clear that the playlist paradigm I built isn’t intuitive.  Let me think if I can present it a better way.

**Comment by janabouc** [comment]
Ok great!

**Comment by sethgecko13** [comment]
Ok, I've roughed out in my head how to handle the playlists.  It's going to take a little bit of rework, probably a couple of days and it should be ready.  Fixed the letter spacing but that won't be available to test until I push the version with playlists.

**Comment by sethgecko13** [comment]
Updated playlists to behave more like YouTube playlists. So you can edit them, create new ones, save them.  The one main difference is when you create YouTube playlists you have to choose the playlists to add a video to each time you try to save a video.  With Meezee you just add a video and it puts it in a new playlist. Then when you're done adding all the videos you can save the playlist.

Also added images to MZ playlists and the ability to import playlists. You can either import a channel's playlist by navigating to the channel, or you can import a playlist by pasting a URL. For example to import your own playlist from your own account.

Also updated the video viewing screen to have better spacing. Words may truncate but should no longer wrap.

The playlist stuff was a pretty big rewrite so I will not be surprised if there are bugs. (Or things that made sense to me but just don't make sense to other people).

Build 2023.10.01 (402). May take up to 24 hours for Apple to approve this build for testing.

**Comment by sethgecko13** [comment]
Closing as fixed.

**Comment by janabouc** [comment]
This is major! Wow! When I finish my 30 day trial on a paid platform I'll be coming back to YouTube and this will mean I won't need to interface directly anymore with YouTube for my classes. 

I will start playing with importing my playlists when the new version is available. 

I've been enjoying getting MZ notifications of new videos posted to my favorite channels.

**Comment by sethgecko13** [comment]
Awesome! Great to hear on all fronts.

I also have the ability to share favorite channels mostly working.  Need to add a few more pieces and test it, but in a couple of days should have it working such that in the app you can save your smart playlist of Pilates channels with the “reformer” filter added and share it with others. 

 People without MZ would get a website with all the videos in the channels you selected and they could filter on duration and add/remove channels and filters and searches just like in the app, but via the web site.

People in the app would just launch into the same smart playlist you see on your end in the app.

**Comment by sethgecko13** [comment]
it still needs some testing and cleanup. But here’s what it looks like if you share a couple of your favorite Pilates channels filtered by “reformer” with other users.

https://meezeefit.com/w/youtube/sp/view?woType=Pilates&title=Pilates&channelIds=UCtt_c8PMrt0ZEE-LF8omc2A,UC-L23-WoVK6GyJLNI-y0qdA,UCshs5pYALu_WHKS6UuMpHNA,&min=270&max=100000&filter=&lifestyle=false&sortBy=-published,&searchFilters=4F8748BA-339E-478E-919D-8A2DEC408AA7,

**Comment by janabouc** [comment]
How (or can) I important a playlist directly from YouTube? (I have a YouTube playlist of reformer videos from across all my favorite channels.) Can i import that playlist? A quick read of the TestFlight updates makes me think playlists have to be by channel but i think i remember you saying you can important playlists from YouTube but i don't remember how or where to find the directions. 

If it is possible, and if after doing so i get a YouTube notification of a new workout and add it to my reformer playlist in YouTube, will it be updated in the one in mz? (I'm guessing no).

**Comment by sethgecko13** [comment]
You can import your YouTube playlist.  If you really want me to tell you how, I will. But I was really hoping it would be intuitive. So… let me know if you don’t see it and I’ll add a how-to?

I will add an option at import time to choose whether to import it as a YouTube playlist (so you continue editing in YouTube) or a MeeZee playlist (so you edit in meezee)

**Comment by janabouc** [comment]
Haha. I found it! "Import from url" and it worked. If you make it a choice to either edit in mz or yt does that mean that if i choose yt i won't be able to arrange/edit/heart in mz?

**Comment by janabouc** [comment]
I just submitted a crash report via TestFlight (?) (popup window after crash). In case this is useful to repeat here:

"I opened a class from my imported playlist, played it for a moment and then i stopped it. I clicked the 3 dots trying to find a way to add it to a schedule but option wasn’t there. Not finding a way i clicked on the Schedule tab and it crashed and closed."

**Comment by janabouc** [comment]
And it crashed again, left bug report after crash that happened after clicking Schedule tab from home i think.

**Comment by sethgecko13** [comment]
> Haha. I found it! "Import from url" and it worked. If you make it a choice to either edit in mz or yt does that mean that if i choose yt i won't be able to arrange/edit/heart in mz?

Yeah. I really want to avoid being in a situation where I have to have people trust me with any of their permissions on YouTube.  Not that I'm untrustworthy, but... the easiest way to be trustworthy is just to never ask for YouTube credentials.  So, to allow editing a YouTube playlist on MZ, I have to either get your permissions to edit the playlist on your behalf and keep it on YouTube, or I have to import it.

Im thinking that just giving you the option of where you would like to primarily manage it is the right middle ground. So keep it on YouTube and edit it there: fine. Import to MZ and edit it there: fine.  Re-export to YouTube if you get tired of MZ: fine.  Keep it on YouTube, let me log into YouTube on your behalf and edit it on your behalf on YouTube: trying to avoid.

**Comment by sethgecko13** [comment]
> And it crashed again, left bug report after crash that happened after clicking Schedule tab from home i think.

Is it crashing 100% of the time you click on schedule tab now?

**Comment by janabouc** [comment]
I tried again. This time it crashed when I went from Schedule to Home: from crash report: 
 "Clicked from Playlist to my imported playlist to Schedule to Home and it crashed"

I tried again doing the same thing and it crashed again.

**Comment by janabouc** [comment]
> > Haha. I found it! "Import from url" and it worked. If you make it a choice to either edit in mz or yt does that mean that if i choose yt i won't be able to arrange/edit/heart in mz?
> 
> Yeah. I really want to avoid being in a situation where I have to have people trust me with any of their permissions on YouTube. Not that I'm untrustworthy, but... the easiest way to be trustworthy is just to never ask for YouTube credentials. So, to allow editing a YouTube playlist on MZ, I have to either get your permissions to edit the playlist on your behalf and keep it on YouTube, or I have to import it.
> 
> Im thinking that just giving you the option of where you would like to primarily manage it is the right middle ground. So keep it on YouTube and edit it there: fine. Import to MZ and edit it there: fine. Re-export to YouTube if you get tired of MZ: fine. Keep it on YouTube, let me log into YouTube on your behalf and edit it on your behalf on YouTube: trying to avoid.

I understand and that makes sense and seems like a reasonable choice.
