### ISSUE TITLE
Update icon to not have off putting sexy woman icon

### ISSUE THREAD

**Issue by sethgecko13** [sethgecko13/MeeZeeFit#5]

**Comment by janabouc** [comment]
Yay!

**Comment by janabouc** [comment]
I see your name is SethGecko. Are you a gecko fan? My son is a gecko breeder. https://www.razzgeckos.com

**Comment by sethgecko13** [comment]
> I see your name is SethGecko. Are you a gecko fan? My son is a gecko breeder. https://www.razzgeckos.com

Hah, no.  Seth Gecko was George Clooney’s character in “From Dusk Til Dawn”

**Comment by janabouc** [comment]
Oh! I like George Clooney but never saw that movie. 🙃

**Comment by sethgecko13** [comment]
Added icon choices to More -> Settings so you can choose a dog icon.  One this version is released I will do some A/B testing in the App Store to see if the dog icon is more popular to determine whether to make this the default.  

Available in test flight as build version 375.

![BlueDog](https://github.com/sethgecko13/MeeZeeFit/assets/75141846/2ce03718-6350-4536-a068-ffb737fa1d18)
![PinkDog](https://github.com/sethgecko13/MeeZeeFit/assets/75141846/a24010de-c4e1-4221-8f13-37834862df30)
![RedDog](https://github.com/sethgecko13/MeeZeeFit/assets/75141846/e85521a8-505e-4330-bd5a-875495007d0e)

**Comment by janabouc** [comment]
I LOVE this! FYI the previous update restored all my customization that disappeared with the version before that. 

I am currently experimenting with free weeks of the various paid (non YouTube) Pilates platforms so won't be playing with Meezee while I'm doing that.

**Comment by sethgecko13** [comment]
Yay! glad you like it. No worries about other apps.  I'll probably release this version out of beta on Thursday, then. Thanks for letting me know. Otherwise I might have tried squeezing in another few features.

If you don't mind taking 10 seconds or so... if you could launch Meezee -> More -> Leave a review and click and appropriate number of stars for it, that would be awesome. Thanks!

**Comment by janabouc** [comment]
If you have any specific questions or things you'd like me to test I'm happy to help. I just won't be using it myself to find classes for a few weeks. 

I'll definitely do an App Store review --after you publish the new public version though, right?

**Comment by janabouc** [comment]
I meant things to test before you publish. I am amazed at all the features and fixes you've already gotten in, including the ipad issue you thought would be challenging.

**Comment by sethgecko13** [comment]
> If you have any specific questions or things you'd like me to test I'm happy to help. I just won't be using it myself to find classes for a few weeks.
> 

Sounds good. No worries.  Nothing specific to test, if you're good with everything so far.

> I'll definitely do an App Store review --after you publish the new public version though, right?

I don't think it matters.  The big thing is hitting a star rating. If you feel a moral need to wait until the latest version is actually published to give it a star rating, that's fine.  But there's nothing in the App Store that prevents you from rating it now, or rating it now and re-rating it later, or leaving a star now and leaving a longer review later, or whatever.  Any thing you can leave is appreciated!

**Comment by sethgecko13** [comment]
> I meant things to test before you publish. I am amazed at all the features and fixes you've already gotten in, including the ipad issue you thought would be challenging.

I've been having a great time.  Having real feedback forced me to fix some stuff that I knew needed to be done, and I lucked out finding the right YouTube documentation on how to fix the iPad issue that I hadn't been able to locate last time I looked at it.  So... thanks so much!
