### ISSUE TITLE
Links, adding to playlist and scrubbing

### ISSUE THREAD

**Issue by janabouc** [sethgecko13/MeeZeeFit#7]
First, great job with the new "playlist"/YouTube playlist options and the new symbols to do so. 

I was a little confused about how to add to a playlist vs the heart symbol. Am I correct that to add to a playlist you have to be in the view with the list of videos, you can't click on a video to preview it and playlist it from there? (Only option is to heart it there, which I think then makes it appear on the Home Screen?) 

I would prefer to be able to playlist from the actual video when I've looked at what's in it rather than then have to go back to the list to add to a playlist. 

I also tried to create and name a playlist but the name never showed up. It is titled "Build Playlist" instead of what I named it "Sample Playlist". 

Scrubbing/previewing: 
I like to quickly scrub through a video to preview it to determine if I want to do it. Is the only way to just keep tapping to move ahead 10 seconds? 

Link to YouTube video: 
I guess this defeats the purpose of MeeZee but I like to watch YouTube workout videos directly via my AppleTV box on my big TV because I can pause/play with my Beats AirPods and also control easily with the iPhone's remote control widget for AppleTV. 

I know MeeZee can airplay but I'd rather use MeeZee for finding videos, making playlists and schedules, and then open the actual YouTube video and play it on ATV. 

Since the MeeZee video won't show in my YouTube history (is that right?) it's a little more work to find it and start it in YouTube. Not a big deal but if there was a link available that would be great!

**Comment by sethgecko13** [comment]
Great feedback as always. Thanks you!

> First, great job with the new "playlist"/YouTube playlist options and the new symbols to do so.
> 
> I was a little confused about how to add to a playlist vs the heart symbol. Am I correct that to add to a playlist you have to be in the view with the list of videos, you can't click on a video to preview it and playlist it from there? (Only option is to heart it there, which I think then makes it appear on the Home Screen?)

> 
> I would prefer to be able to playlist from the actual video when I've looked at what's in it rather than then have to go back to the list to add to a playlist.

I added the ability to add to playlist back to the video player screen.

> 
> I also tried to create and name a playlist but the name never showed up. It is titled "Build Playlist" instead of what I named it "Sample Playlist".

Fixed.

> 
> Scrubbing/previewing: I like to quickly scrub through a video to preview it to determine if I want to do it. Is the only way to just keep tapping to move ahead 10 seconds?

When I view a video on my end on an , it fullscreens and I have normal YouTube video controls to go forward or backward.

However, on an iPad those controls are not there. I'm not sure there is an easy way to fix this. I'm going to open a new ticket just for this on iPad. 

> 
> Link to YouTube video: I guess this defeats the purpose of MeeZee but I like to watch YouTube workout videos directly via my AppleTV box on my big TV because I can pause/play with my Beats AirPods and also control easily with the iPhone's remote control widget for AppleTV.

Added. I'm not going to explain how, though, in case the way it was intuitive to me to add isn't intuitive to you.
> 
> I know MeeZee can airplay but I'd rather use MeeZee for finding videos, making playlists and schedules, and then open the actual YouTube video and play it on ATV.
> 
> Since the MeeZee video won't show in my YouTube history (is that right?) 

correct. But the correct link to open the video in YouTube *hopefully* fixes this, if Im understanding what you're doing correctly.

> it's a little more work to find it and start it in YouTube. Not a big deal but if there was a link available that would be great!

Closing this with build

**Comment by sethgecko13** [comment]
https://github.com/sethgecko13/MeeZeeFit/issues/8

Scrubbing issue fixed with build 374
